version: '3'

services:
    db:
        image: postgres:11
        restart: always
        environment:
            POSTGRES_DB: flats
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/pg/flats:/var/lib/postgresql:delegated

