version: '3'

services:
    db:
        image: postgres:11
        restart: always
        environment:
            POSTGRES_DB: flats
        ports:
          - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql:delegated

volumes:
    postgres:
        driver: local
